apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  name: kokoji-app-pvc
  namespace: kokoji-project01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi